---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1097836308413/locations/global/workloadIdentityPools/gh-pool/providers/github-provider
          service_account: smg-exercise-big-query@fastapi-320118.iam.gserviceaccount.com
      - name: Test
        run: docker-compose run --rm app sh -c "pytest"
